/****************************************************
                   DO NOT EDIT! 
   Automatically generated by 'scripts/genconfig.pl'
              Wed Jun 27 15:34:54 2012
*****************************************************/

#ifndef CONFIG_OPTIONS
#define CONFIG_OPTIONS

#define CONFIG_STACK_SIZE 8192
#define CONFIG_PANIC_STRING "  AKOSIX KERNEL PANIC  "
#define CONFIG_ENABLE_CONSOLE
#define CONFIG_CONSOLE_WIDTH 80
#define CONFIG_CONSOLE_HEIGHT 25

#endif /* CONFIG_OPTIONS */
