/****************************************************
                   DO NOT EDIT! 
   Automatically generated by 'scripts/genconfig.pl'
              Fri May 25 20:34:15 2012
*****************************************************/

#ifndef CONFIG_OPTIONS
#define CONFIG_OPTIONS

#define CONFIG_STACK_SIZE 8192
#define CONFIG_PANIC_STRING "  AKOSIX KERNEL PANIC  "
#define CONFIG_ENABLE_CONSOLE
#define CONFIG_CONSOLE_WIDTH 80
#define CONFIG_CONSOLE_HEIGHT 25
#define CONFIG_DEBUG_KMALLOC

#endif /* CONFIG_OPTIONS */
