#########################################################################
#   Copyright (c) 2012 Ákos Kovács - Akosix operating system
#              http://akoskovacs.github.com/Akosix
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
#########################################################################
#!/usr/bin/perl 

use strict;
use warnings;

my $CONFIG_NAME = ".config" unless $ARGV[0];
my $HEADER_NAME = "config.h" unless $ARGV[1];

my $TIME = localtime(time());
my $out_header = <<EOH;
/****************************************************
                   DO NOT EDIT! 
   Automatically generated by 'scripts/genconfig.pl'
              $TIME
*****************************************************/

#ifndef CONFIG_OPTIONS
#define CONFIG_OPTIONS

EOH

open(CONF, '<' . $CONFIG_NAME) or die "You must run the \'make config\'!";
open(HEADER, '>' . $HEADER_NAME) or die "Cannot create $HEADER_NAME: $!";

print HEADER $out_header;

while (<CONF>) {
    if (/^#/ or $_ eq "") {
        next;
    } elsif (/(.+)=(.+)/) {
        if ($2 eq "y") {
            print HEADER "#define $1\n"
        } else {
            print HEADER "#define $1 $2\n";
        }
    }
}
print HEADER "\n#endif /* CONFIG_OPTIONS */\n";
close CONF;
close HEADER;
